### ISSUE TITLE
bsd_mem.h isn't part of Haiku anymore

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/BeCJK#4]
Hence the build fails not finding it, removed in: https://github.com/haiku/haiku/commit/3b4737b9e511bd2fb595eea1fd33c28e7e2b2add

**Comment by c6767** [comment]
so
if i want to use BeCJK,
what can i do ?
rebuild all HaikuOS?

**Comment by Begasus** [comment]
Should be fixed in https://github.com/haikuports/haikuports/pull/7429, could you check and report back?

**Comment by Begasus** [comment]
Reported fixed, closing.
